{
 "title": "Service Graph",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "productCui",
    "label": "CUI",
    "query": {
     "query": "label_values(anomaly:all,productCui)"
    }
   },
   { "name": "anomaly_name", "label": "Type", "query": { "query": "label_values(anomaly_name)" } }
  ]
 },
 "panels": [
  {
   "title": "CUI Abnormal Span Ratio",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(avg by(productCui) (anomaly:present{productCui=~\"$productCui\", anomaly_name=\"$anomaly_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomaly Series",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(anomaly:select{anomaly_name=~\"$anomaly_name\",productCui=~\"$productCui\"}) without ( anomaly_select)",
     "legendFormat": "{{productCui}} {{client}} -> {{server}} ({{anomaly_name}})"
    }
   ]
  },
  {
   "title": "Spans With Anomaly",
   "type": "nodeGraph",
   "gridPos": { "h": 34, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n  label_join(\n    label_join(\n      sum(anomaly:all{anomaly_name=~\"$anomaly_name\",productCui=~\"$productCui\"}) by (client)\n      , \"id\", \"\", \"client\"\n    )\n    , \"title\", \"\", \"client\"\n  )\n  , \"icon\", \"cube\", \"\", \"\"\n)) without(client,server,anomaly_name,anomaly_select,anomaly_type)\nor\nsum(\n  label_replace(\n  label_join(\n    label_join(\n      sum(anomaly:all{anomaly_name=~\"$anomaly_name\",productCui=~\"$productCui\"}) by (server)\n      , \"id\", \"\", \"server\"\n    )\n    , \"title\", \"\", \"server\"\n  )\n  , \"icon\", \"cube\", \"\", \"\"\n)) without(client,server,anomaly_name,anomaly_select,anomaly_type)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "# receivers -> processor\nsum(\nlabel_replace(\nlabel_join(\n    label_join(\n        label_join(\n            sum(anomaly:present{anomaly_name=~\"$anomaly_name\",productCui=~\"$productCui\"}) by (client, server)>=1,\n            \"source\", \"\", \"client\"\n        )\n        ,\"target\", \"\", \"server\"\n    )\n    , \"id\", \"-\", \"source\", \"target\"\n    )\n    , \"color\", \"red\", \"\", \"\"\n)) without(client,server)\nor\n# receivers -> processor\nsum(\nlabel_replace(\nlabel_join(\n    label_join(\n        label_join(\n            sum(anomaly:present{anomaly_name=~\"$anomaly_name\",productCui=~\"$productCui\"}) by (client, server)==0,\n            \"source\", \"\", \"client\"\n        )\n        ,\"target\", \"\", \"server\"\n    )\n    , \"id\", \"-\", \"source\", \"target\"\n    )\n    , \"color\", \"green\", \"\", \"\"\n)) without(client,server)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}