groups:
  - name: AnomalyOTELDemoCUIServiceGraphMetrics
    rules:

      ################################################################################
      #                     RED servicegraph metrics (with CUI)                      #
      ################################################################################

      - record: anomaly:request:rate5m
        expr: sum(label_replace(rate(traces_service_graph_request_total{server!="unknown",client!="unknown",server_productCui!=""}[5m]),"productCui", "$1", "server_productCui", "(.*)")) without(client_productCui,server_productCui,failed)
        labels:
          anomaly_name: "requests_with_cui"
          anomaly_type: "requests"

      - record: anomaly:request:latency:p50
        expr: histogram_quantile(0.50, sum (label_replace(rate(traces_service_graph_request_client_seconds_bucket{server!="unknown",client!="unknown",server_productCui!=""}[5m]),"productCui", "$1", "server_productCui", "(.*)")) without(client_productCui,server_productCui,failed))
        labels:
          anomaly_name: "latency_p50_with_cui"
          anomaly_type: "latency"

      - record: anomaly:request:errors
        expr: |-
          sum(label_replace(rate(traces_service_graph_request_failed_total{server!="unknown",client!="unknown",server_productCui!=""}[5m]),"productCui", "$1", "server_productCui", "(.*)")) without(client_productCui,server_productCui,failed)
          OR
          sum(label_replace(rate(traces_service_graph_request_total{server!="unknown",client!="unknown",server_productCui!=""}[5m]),"productCui", "$1", "server_productCui", "(.*)")) without(client_productCui,server_productCui,failed) * 0
        labels:
          anomaly_name: "errors_with_cui"
          anomaly_type: "errors"

  - name: AnomalyOTELDemoServiceGraphMetrics
    rules:

      ################################################################################
      #                     RED servicegraph metrics (without CUI)                   #
      ################################################################################

      - record: anomaly:request:rate5m
        expr: sum(rate(traces_service_graph_request_total{server!="unknown",client!="unknown",server_productCui!=""}[5m])) without(client_productCui,server_productCui,failed)
        labels:
          anomaly_name: "requests"
          anomaly_type: "requests"

      - record: anomaly:request:latency:p50
        expr: histogram_quantile(0.50, sum (rate(traces_service_graph_request_client_seconds_bucket{server!="unknown",client!="unknown",server_productCui!=""}[5m])) without(client_productCui,server_productCui,failed))
        labels:
          anomaly_name: "latency_p50"
          anomaly_type: "latency"

      - record: anomaly:request:errors
        expr: |-
          sum(rate(traces_service_graph_request_failed_total{server!="unknown",client!="unknown",server_productCui!=""}[5m])) without(client_productCui,server_productCui,failed)
          OR
          sum(rate(traces_service_graph_request_total{server!="unknown",client!="unknown",server_productCui!=""}[5m])) without(client_productCui,server_productCui) * 0
        labels:
          anomaly_name: "errors"
          anomaly_type: "errors"

